### PR TITLE
c is usable, added printf

### PR DESCRIPTION
**Pull request by daniyalw**
Using GRUB, C is now usable, and I added a few functions such as printf(), strlen(), and itoa()

### CODE REVIEW

**Comment by julySteuer** [comment]
That was quick and what are your sources bcs i do not understand a word

**Comment by daniyalw** [comment]
I got them from my operating system.

**Comment by julySteuer** [comment]
A 14 year old who can make operating systems. I get imposter syndrom

**Comment by daniyalw** [comment]
Should I open source the code?

**Comment by daniyalw** [comment]
Done, open sourced

**Pull request merged**
